#!/bin/bash

# Prints its first argument...
# Adds a 1 second cooldown...
log() {
    for arg in "$@"; do
        echo -e "$arg"
        sleep .5
    done
}

# Handle errors by logging them fisrt...
# then exit the script with a non-zero exit code
error() {
    log "ERROR: $1" "Exiting..."
    exit 1
}

# Adds files, then commits with a autogenerated message, then pushes...
# All in a defined time interval...
# Not used, needs further investigations...
# Requires commit_and_push() to be desactivated...
auto_push() {
    i=1
    while true; do
        if [[ -n $(git status -s) ]]; then
            add_files "$@"
            log "Status:"
            git status
            git commit -a -m "Auto Commit - $i"
            git push origin master
            i=$((i + 1))
        fi
        sleep 1200
    done
}
